### ISSUE TITLE
Replace '\n' with ' ' to cleanup page_html

### ISSUE THREAD

**Issue by mustiikhalil** [codeGUST-SE/codeGUST#17]

**Comment by evis-e** [comment]
I think '\n' is saved as two characters. In case we actually need to know where we have newlines, we can replace it with the actual newline char. Also, we could look for consecutive spaces or newlines and compress them to only a since space or new line?

**Comment by mustiikhalil** [comment]
formatted the text and removed unnecessary chars

**Comment by mustiikhalil** [comment]
Check the new implementation

**Comment by evis-e** [comment]
I just realized that we are replacing consecutive spaces with a single space while some programmers actually use multiple spaces to indent their code :P I believe that during indexing the spaces or tabs or newlines wont matter (we will only probably use the position of the word in the document) so I think we can safely replace all that matches /\s+/ with space.

**Comment by mustiikhalil** [comment]
Great Job
